default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development

test:
  <<: *default
  database: rails-watch-list_test


production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DATABASE_URL'].sub(/^.*\/(.*?)$/, '\1') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
